### ISSUE TITLE
React - Webpack warning on build

### ISSUE THREAD

**Issue by etienne-mobsuccess** [aws/aws-iot-device-sdk-js-v2#323] opened 2023-01-26 10:40 UTC
### Describe the bug

When we build our react webapp using webpack (version 5.5.0) we have a lots of warnings in the output :

```
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/auth.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/auth.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/auth.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/aws_iot.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/aws_iot.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/aws_iot.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/aws_iot_mqtt5.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/aws_iot_mqtt5.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/aws_iot_mqtt5.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/crypto.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/crypto.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/crypto.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/error.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/error.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/error.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/http.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/http.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/http.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/io.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/io.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/io.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/iot.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/iot.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/iot.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/mqtt.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/mqtt.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/mqtt.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/mqtt5.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/mqtt5.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/mqtt5.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/mqtt5_utils.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/mqtt5_utils.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/mqtt5_utils.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/trie.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/trie.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/trie.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/browser/ws.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/ws.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/browser/ws.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/aws_iot_shared.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/aws_iot_shared.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/aws_iot_shared.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/event.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/event.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/event.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/http.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/http.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/http.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/io.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/io.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/io.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/mqtt.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/mqtt_shared.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt_shared.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt_shared.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/mqtt5.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt5.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt5.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/mqtt5_packet.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt5_packet.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/mqtt5_packet.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/platform.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/platform.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/platform.ts'
[1] 
[1] WARNING in ./node_modules/aws-crt/dist.browser/common/resource_safety.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/resource_safety.ts' file: Error: ENOENT: no such file or directory, open '/Users/etiennevenot/Projects/platform-lcm/node_modules/aws-crt/lib/common/resource_safety.ts'
```

We can disable them by configuring webpack to not generate source-map but we need the source-map in our case and we want to keep them.

Does anyone know the correct webpack configuration to use with `aws-iot-device-sdk-js-v2` to avoid the issue ?

Thanks !

### Expected Behavior

Allow to use webpack 5 with source-map generation with no warnings.

### Current Behavior

Warnings with source-map generation

### Reproduction Steps

`npm i aws-iot-device-sdk-v2@latest`
`npm start`

You'll see the warnings

### SDK version used

1.9.2

### Environment details (OS name and version, etc.)

macos / linux / docker

**Comment by pierresisson** [comment] 2023-01-31 14:52
same problems, up ?

**Comment by jmklix** [comment] 2023-01-31 19:42
Do the warnings stop you from using this sdk correctly?

**Comment by Maastrich** [comment] 2023-02-01 09:11
Same problem
@jmklix no, the library still work but the problem is that source-maps are provided but they refer to unexisting sources, one fix would be to delete the source-maps

**Comment by pierresisson** [comment] 2023-02-01 09:15
hi @jmklix nop, it works but working with errors is a non-sense

**Comment by jmklix** [comment] 2023-02-03 23:49
Sorry, these warnings might be a little annoying. We do have plans to fix them and officially support the [React framework](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/331).

**Comment by jmklix** [comment] 2023-02-23 21:27
Closing this as it is a duplicate of the [React Support feature request](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/331). Please let us know if you still run into this error after support is officially added

**Closed by jmklix** 2023-02-23 21:27 UTC
Labels: feature-request, duplicate, p3
