### ISSUE TITLE
Support for custom authentication when using WebSocket connection

### ISSUE THREAD

**Issue by tporter-signiant** [aws/aws-iot-device-sdk-js-v2#294] opened 2022-10-25 01:24 UTC
### Describe the feature

Currently, it appears that the use of custom authentication while connecting to AWS IoT using MQTT over WebSockets is non-functional or unsupported by the SDK.

I've had success making IoT connections using the following combination:

- Signature V4 authentication with MQTT
- Signature V4 authentication with MQTT over WebSockets
- Custom authentication with MQTT

Trying a configuration that mixes both custom authentication and WebSockets appears to break things. Sample code of what I'm trying to do:

```
const iotSdk = require('aws-iot-device-sdk-v2');

iotSdk.io.enable_logging(iotSdk.io.LogLevel.INFO);
const clientBootstrap = new iotSdk.io.ClientBootstrap();

const endpoint = '<iot-endpoint>';
const clientId = '<client-id>';
const token = '<token>'
const username = `?x-token=${token}`;
const authorizerName = '<authorizer-name>';
const signature = encodeURIComponent(<signature>);

const config = iotSdk.iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets()
    .with_custom_authorizer(username, authorizerName, signature)
    .with_endpoint(endpoint)
    .with_client_id(clientId)
    .build();

const client = new iotSdk.mqtt.MqttClient(clientBootstrap);
connection = client.new_connection(config);

connection.connect().catch((err) => {
    console.log(err.message);
});
```

Log output that may be relevant:

```
[WARN] [2022-10-25T00:58:40Z] [0000700005f43000] [http-connection] - static: Unrecognized ALPN protocol. Assuming HTTP/1.1
[INFO] [2022-10-25T00:58:40Z] [0000700005f43000] [http-connection] - id=0x7fbc46999dd0: HTTP/1.1 client connection established.
[ERROR] [2022-10-25T00:58:40Z] [0000700005f43000] [tls-handler] - id=0x7fbc46847e00: error reported during SSLRead. OSStatus code -9805
[INFO] [2022-10-25T00:58:40Z] [0000700005f43000] [http-connection] - 0x7fbc46999dd0: Client shutdown completed with error 0 (AWS_ERROR_SUCCESS).
[ERROR] [2022-10-25T00:58:40Z] [0000700005f43000] [websocket-setup] - id=0x7fbc45f9ef60: Websocket setup failed, error 3 (AWS_ERROR_UNKNOWN).
```
### Use Case

Custom authentication with WebSockets should be part of the SDK as it was supported in v1

### Proposed Solution

More detailed documentation and/or sample code that demonstrates exactly how to accomplish this combination or confirmation that this is currently not possible in the SDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.8.9

### Environment details (OS name and version, etc.)

MacOS 12.6

**Comment by TwistedTwigleg** [comment] 2022-10-25 15:10
Thank you for reporting this issue! I have tested and confirmed it is not working. I made a [fix in the Javascript CRT](https://github.com/awslabs/aws-crt-nodejs/pull/362), which once merged and released, the SDK can be updated with the fix.

**Comment by tporter-signiant** [comment] 2022-10-25 16:00
Our use case is for an on-premises server product that uses IoT to receive real-time requests from a cloud control plane. Because of the potential for various firewall configurations that customers may have in place that we have no control over and the need for HTTP proxy support we use MQTT over WebSockets. Our authentication method uses a JWT token signed by a private key on the server.

**Closed** 2022-12-13 14:10 UTC
Labels: bug, p2

**Comment by nebbles** [comment] 2022-12-21 15:18
> Our use case is for an on-premises server product that uses IoT to receive real-time requests from a cloud control plane. Because of the potential for various firewall configurations that customers may have in place that we have no control over and the need for HTTP proxy support we use MQTT over WebSockets. Our authentication method uses a JWT token signed by a private key on the server.

@bretambrose great to see this patched up. I've literally been going through the same thing here, with (high-performance) IoT devices deployed on-premise at enterprise customer sites. I've had challenges with connection disruption compounded with timeout issues (a somewhat separate issue, need to try reconfiguring timeouts), and most recently hit up against TLS handshake failing at a new customer site (we use X509 certs for auth currently).

I'm now investigating moving over our device clients to using MQTT over WebSockets as a means to avoid the MQTT protocol, 8883 port, and mTLS because it seems there are just too many landmines on enterprise networks that could slow our deployments down (and we've never had an issue with our WebSocket connections that operate via 443).

**Comment by bretambrose** [comment] 2022-12-21 20:18
I was initially resistant because at a coarse level it feels like custom-auth-over-websockets and custom-auth-over-direct-mqtt are indistinguishable (tls-wrapped, port 443).  But I'm not an IT guru and it seems likely that there are network configurations which (although creepy) can distinguish between the two (mandatory MITM proxies, for example) and its more helpful to developers to just support both.

Anyways, Noah did all the work.
