### ISSUE TITLE
Unable to use IotShadowClient in the browser

### ISSUE THREAD

**Issue by rk-yen** [aws/aws-iot-device-sdk-js-v2#222] opened 2022-02-16 21:40 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Describe the bug**
Unable to use IotShadowClient in the browser.

**SDK version number**
Tried 1.7.0 and 1.6.5

**Platform/OS/Hardware/Device**
Webapp running via "create-react-app" inside a Chrome Browser.

**To Reproduce (observed behavior)**
```
    const config = constructIotConfig(
      userInfo,
      accessKeyId,
      secretKey,
      sessionToken
    );
    const client = new mqtt.MqttClient();
    const iotConnection = client.new_connection(config);
    const iotShadowClient = new iotshadow.IotShadowClient(iotConnection.current);
```

**Expected behavior**
Expect the shadow client to be created.

**Logs/output**
Instead, see an exception
![Screen Shot 2022-02-16 at 3 34 41 PM](https://user-images.githubusercontent.com/4944665/154360966-ea1ef537-efd6-40a7-96cb-f8fc6e052f6b.png)

The screenshot below shows the usage of "util".
![Screen Shot 2022-02-16 at 3 35 34 PM](https://user-images.githubusercontent.com/4944665/154361082-f071a494-35fa-42eb-942a-a849a85e8362.png)

**Additional context**
* Corresponding code: https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/lib/iotshadow/iotshadowclient.ts#L15
* I see some polyfills defined in aws-crt at https://github.com/awslabs/aws-crt-nodejs/blob/main/lib/browser/polyfills.ts.
* Within my code, if I use `const iotPayloadDecoder = new TextDecoder();`, then that works fine.

**Comment by b3kN** [comment] 2022-03-05 23:04
bump .

**Comment by jmklix** [comment] 2023-02-23 21:34
Closing this as it is a duplicate of the [React Support feature request](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/331). Please let us know if you still run into this error after support is officially added

**Closed by jmklix** 2023-02-23 21:34 UTC
Labels: feature-request, p2
