### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by vidaljuanp** [aws/aws-iot-device-sdk-js-v2#295] opened 2022-10-29 09:54 UTC
### Describe the bug

React app breaks after installing aws-iot-device-sdk-v2

All I do is 
1. Create a new app 
npx create-react-app my-app

2. install the the library
npm install aws-iot-device-sdk-js-v2

3. include the library to use in the app 
import { mqtt } from 'aws-iot-device-sdk-v2';

and the app breaks with the error:
```
constants.js:46 Uncaught ReferenceError: Buffer is not defined
    at ./node_modules/mqtt-packet/constants.js (constants.js:46:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/mqtt-packet/parser.js (parser.js:4:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/mqtt-packet/mqtt.js (mqtt.js:1:1)
    at options.factory (react refresh:6:1)
```

I want to create a react app that subscribes to an AWS MQTT topic  to get updates in real time. But here is no where to find a proper example to do this. 

### Expected Behavior

the app shouldn't break

### Current Behavior
```
constants.js:46 Uncaught ReferenceError: Buffer is not defined
    at ./node_modules/mqtt-packet/constants.js (constants.js:46:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/mqtt-packet/parser.js (parser.js:4:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/mqtt-packet/mqtt.js (mqtt.js:1:1)
    at options.factory (react refresh:6:1)
```
### Reproduction Steps

1. Create a new app 
npx create-react-app my-app

2. install the the library
npm install aws-iot-device-sdk-js-v2

3. include the library to use in the app 
import { mqtt } from 'aws-iot-device-sdk-v2';

and the app breaks with the error:
```
constants.js:46 Uncaught ReferenceError: Buffer is not defined
    at ./node_modules/mqtt-packet/constants.js (constants.js:46:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/mqtt-packet/parser.js (parser.js:4:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/mqtt-packet/mqtt.js (mqtt.js:1:1)
    at options.factory (react refresh:6:1)
```

### Additional Information/Context

    "aws-amplify": "^4.3.42",
    "aws-iot-device-sdk-v2": "^1.8.9",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",

### SDK version used

"aws-iot-device-sdk-v2": "^1.8.9",

### Environment details (OS name and version, etc.)

Mac OS 12.2.1

**Comment by croraf** [comment] 2022-12-05 09:31
This can be solved with a webpack hack. 
Check https://github.com/facebook/create-react-app/issues/11756
The solution with `craco` worked for me.

**Comment by jmklix** [comment] 2022-12-06 18:59
> Found a pretty simple workaround that's been working for my projects without having to eject or use react-app-rewired/craco.
> 
> So instead of having Webpack polyfil these missing node code dependencies, just have NPM install the polyfils as the named packages directly.
> You can specify the versions too. Example:
> 
> ```
> "devDependencies": {
>   "buffer": "npm:buffer@6.0.3",
>   "crypto": "npm:crypto-browserify@3.12.0",
>   "stream": "npm:stream-browserify@3.0.0",
>   "util": "npm:util@0.12.5",
> }
> ```
> 
> This will create a package within node_modules matching the dev dependency name, but with the npm import code. Example:
> 
> ```
> node_mudules/crypto/package.json => "name": "crypto-browserify"
> ```
> 
> There's a little extra work to polyfil some window values like Buffer, I solved this by having an import within the app before it gets used:
> 
> ```
> import { Buffer } from 'buffer';
> 
> // If we don't have a value for Buffer (node core module) create it/polyfill it
> if (window.Buffer === undefined) window.Buffer = Buffer;
> ...
> ```
> 
> Using the above, I can stay on the latest React and React Scripts versions without having to touch the Webpack config at all.

This is the fix mentioned by croraf. Does this work for you with this sdk?

**Comment by croraf** [comment] 2022-12-09 11:32
> This is the fix mentioned by croraf. Does this work for you with this sdk?

Actually that polyfil does not work for me. This works for me: https://github.com/facebook/create-react-app/issues/11756#issuecomment-1001162736

**Comment by jmklix** [comment] 2023-01-05 19:41
@vidaljuanp are you able to build your react app with either fix listed above?

**Comment by vidaljuanp** [comment] 2023-01-08 09:56
> 

I decided to go with Amplify pubsub. It was quite frustrating for me to work with this library and see that it doesn't work with the a very basic example and also I couln't find examples on how to use this new version. thanks to everyone who helped with the answers and comments

**Comment by ymwjbxxq** [comment] 2023-02-03 14:57
still not working whatever is the solution always fails with the latest versions

**Comment by jmklix** [comment] 2023-02-03 23:51
Sorry that you are still running into this error. This sdk currently doesn't support React framework, but it is something that we are [working on](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/331).

**Comment by jmklix** [comment] 2023-02-23 21:31
Closing this as it is a duplicate of the https://github.com/aws/aws-iot-device-sdk-js-v2/issues/331. Please let us know if you still run into this error after support is officially added

**Closed by jmklix** 2023-02-23 21:31 UTC
Labels: feature-request, duplicate, p2
