### ISSUE TITLE
Unable to handle/catch aws-crt error Connection closed

### ISSUE THREAD

**Issue by Epick362** [aws/aws-iot-device-sdk-js-v2#302] opened 2022-12-05 10:10 UTC
### Describe the bug

We observe in our logs a lot of Error: Connection closed errors that originate from aws-crt but do not seem to be handled by any of the connection.on listeners ('error', 'interrupt', 'disconnect'). 

![image](https://user-images.githubusercontent.com/1021662/205609488-cb30b9fe-4c94-4e85-87a2-ef708c1298bb.png)

I do not know where I could catch this error and handle it in app. Could anyone please advise?

### Expected Behavior

To be able to catch this error and attempt a reconnect

### Current Behavior

No way to catch this Error: Connection closed.

### Reproduction Steps

Unsure about specific steps but AFAIK happens with long-lived connections.

### SDK version used

1.8.5

### Environment details (OS name and version, etc.)

React Native, iOS+Android

**Comment by jmklix** [comment] 2023-01-04 19:45
Can you enable the cloudwatch logs to see why the connection is being closed?
>You can also enable [CloudWatch logging](https://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html) for IoT which will provide you with additional information that is not available on the client side sdk.

This won't allow you to handle it in your application, but it will help us determine what the cause is.

**Comment by Epick362** [comment] 2023-01-05 09:22
Thank you for this tip. I enabled the logs and will report back with findings.

**Comment by Epick362** [comment] 2023-01-17 10:51
Hello, reviving this as I have not found any specific error messages in the logs pointing to this issue.
The main problem is not that the connection closes but that it emits an Error on the client side that I am not able to catch anywhere in code and it generates a ton of Sentry reports etc.

**Comment by jmklix** [comment] 2023-02-23 21:33
Closing this as it is a duplicate of the [React Support feature request](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/331). Please let us know if you still cant handle aws-crt errors correctly after official react support is added

**Closed by jmklix** 2023-02-23 21:33 UTC
Labels: feature-request, p2
