### ISSUE TITLE
MQTT infinite reconnection

### ISSUE THREAD

**Issue by cupostv** [aws/aws-iot-device-sdk-js-v2#78] opened 2020-07-27 14:49 UTC
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on? Primarly Raspberry PI. For testing purposes Windows 10.

**Describe the question**
I am creating a MQTT connection like this:
```
    const client_bootstrap = new io.ClientBootstrap();

    let config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path(config.aws.cert_path, config.aws.key_path);

    config_builder.with_certificate_authority_from_path(undefined, config.aws.root_ca_path);

    config_builder.with_clean_session(false);
    config_builder.with_client_id(config.aws.thing_name);
    config_builder.with_endpoint(config.aws.iot_endpoint);

    const mqttConfig = config_builder.build();

    const client = new mqtt.MqttClient(client_bootstrap);
    connection = client.new_connection(mqttConfig);

    shadow = new iotshadow.IotShadowClient(connection);

    thingName = config.aws.thing_name;

    return connection.connect();
```
Everything works perfectly when there is connection. If i disconnect from internet, after sometime (20-30 seconds) i will get `interrupt` event with the following error:

```
CrtError: aws-c-io: AWS_IO_SOCKET_CLOSED, socket is closed.
    at MqttClientConnection._on_connection_interrupted (/home/mstupar/device/node_modules/aws-crt/dist/native/mqtt.js:334:32)
    at /home/mstupar/device/node_modules/aws-crt/dist/native/mqtt.js:114:113 {
  error: 1051,
  error_code: 1051,
  error_name: 'AWS_IO_SOCKET_CLOSED'
}
```
If I connect to internet after this interrupt, i will get an unhandled exception with the following stacktrace:
```
################################################################################
Resolved stacktrace:
################################################################################
0x00007fc3193b781b: ?? ??:0
0x00000000000b1383: s_print_stack_trace at module.c:?
0x00000000000128a0: __restore_rt at ??:?
0x00007fc31c4bef47: ?? ??:0
0x00007fc31c4c08b1: ?? ??:0
node() [0x95c589]
node(napi_acquire_threadsafe_function+0x27) [0x9cf1e7]
0x00007fc3192f1931: ?? ??:0
0x00000000000b4306: s_on_connection_resumed at mqtt_client_connection.c:?
0x00000000000de34c: s_packet_handler_connack at client_channel_handler.c:?
0x00000000000dee9e: s_process_read_message at client_channel_handler.c:?
0x000000000011269d: s_s2n_handler_process_read_message at s2n_tls_channel_handler.c:?
0x0000000000113bbe: s_do_read at socket_channel_handler.c:?
0x00000000001141f2: s_on_readable_notification at socket_channel_handler.c:?
0x0000000000110a5a: s_on_socket_io_event at socket.c:?
0x000000000010bb9a: s_main_loop at epoll_event_loop.c:?
0x0000000000177c1b: thread_fn at thread.c:?
0x00000000000076db: start_thread at ??:?
0x00007fc31c5a1a3f: ?? ??:0
################################################################################
Raw stacktrace:
################################################################################
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_backtrace_print+0x4b) [0x7fc3193b781b]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xb1383) [0x7fc3192f1383]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0) [0x7fc31c8928a0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7fc31c4bef47]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7fc31c4c08b1]
node() [0x95c589]
node(napi_acquire_threadsafe_function+0x27) [0x9cf1e7]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_napi_queue_threadsafe_function+0x11) [0x7fc3192f1931]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xb4306) [0x7fc3192f4306]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xde34c) [0x7fc31931e34c]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xdee9e) [0x7fc31931ee9e]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x11269d) [0x7fc31935269d]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x113bbe) [0x7fc319353bbe]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x1141f2) [0x7fc3193541f2]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x110a5a) [0x7fc319350a5a]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x10bb9a) [0x7fc31934bb9a]
/home/mstupar/device/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x177c1b) [0x7fc3193b7c1b]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fc31c8876db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fc31c5a1a3f]
```
Is it possible to avoid AWS_IO_SOCKET_CLOSED with additional configuration?
How should I properly reconnect? Is there some automatic way like socket.io has.
The device should be able to run at least 1 day without restart. In that day, multiple connection losses may occur. Process restart with `systemd` is not good solution for this case because i am running some other modules in the same process that should not be affected with connection loss.

Is there any additional configuration needed for MqttClientConnection?
Should I call some functions from `interrupt` to resume connection manually?

Thanks in advance,
Mladen Stupar

**Comment by TingDaoK** [comment] 2020-08-11 06:02
Sorry for the late response. SDK should reconnect automatically, it seems like a bug... To help us reproduce the error, can you provide which version of SDK you are currently using?

**Comment by jarredkenny** [comment] 2020-08-17 13:56
I am also having trouble with this, if I disconnect and reconnect my network with an MQTT connection the process dies with the following:

```
[INFO ] [2020-08-17T13:36:04Z] [00007f629883fb40] [dns] - id=0x3a87988e9768: Initializing default host resolver with 64 max host entries.
[INFO ] [2020-08-17T13:36:04Z] [00007f629883fb40] [channel-bootstrap] - id=0x3a87988dbb40: Initializing client bootstrap with event-loop group 0x7f6282203920
[INFO ] [2020-08-17T13:36:04Z] [00007f629883fb40] [mqtt-client] - id=0x3a87987f3000: using ping timeout of 3000000000 ns
[WARN ] [2020-08-17T13:36:04Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[ERROR] [2020-08-17T13:36:04Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: connect failed with error code 101.
[INFO ] [2020-08-17T13:36:04Z] [00007f6281c5a700] [dns] - id=0x3a87988e9768: recording failure for record 2600:1f00:6000::30e:21f3 for a1lhfls3yg5tly-ats.iot.us-east-2.amazonaws.com, moving to bad list
[ERROR] [2020-08-17T13:36:04Z] [00007f6281c5a700] [channel-bootstrap] - id=0x3a87988dbb40: failed to create socket with error 1049
[WARN ] [2020-08-17T13:36:04Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[INFO ] [2020-08-17T13:36:05Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: connection success
(node:6636) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[ERROR] [2020-08-17T13:43:08Z] [00007f6281c5a700] [mqtt-client] - id=0x3a87987f3000: ping timeout detected
[ERROR] [2020-08-17T13:43:08Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[WARN ] [2020-08-17T13:43:08Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[ERROR] [2020-08-17T13:43:08Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: connect failed with error code 101.
[INFO ] [2020-08-17T13:43:08Z] [00007f6281c5a700] [dns] - id=0x3a87988e9768: recording failure for record 2600:1f00:6000::317:f90c for a1lhfls3yg5tly-ats.iot.us-east-2.amazonaws.com, moving to bad list
[ERROR] [2020-08-17T13:43:08Z] [00007f6281c5a700] [channel-bootstrap] - id=0x3a87988dbb40: failed to create socket with error 1049
[WARN ] [2020-08-17T13:43:08Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[ERROR] [2020-08-17T13:43:08Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: connect failed with error code 101.
[INFO ] [2020-08-17T13:43:08Z] [00007f6281c5a700] [dns] - id=0x3a87988e9768: recording failure for record 3.23.249.12 for a1lhfls3yg5tly-ats.iot.us-east-2.amazonaws.com, moving to bad list
[ERROR] [2020-08-17T13:43:08Z] [00007f6281c5a700] [channel-bootstrap] - id=0x3a87988dbb40: failed to create socket with error 1049
[ERROR] [2020-08-17T13:43:09Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:09Z] [00007f627bc0d700] [channel-bootstrap] - id=0x3a87988dbb40: dns resolution failed, or all socket connections to the endpoint failed.
[ERROR] [2020-08-17T13:43:10Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:11Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:11Z] [00007f627bc0d700] [channel-bootstrap] - id=0x3a87988dbb40: dns resolution failed, or all socket connections to the endpoint failed.
[ERROR] [2020-08-17T13:43:12Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:13Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:14Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:15Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:15Z] [00007f627bc0d700] [channel-bootstrap] - id=0x3a87988dbb40: dns resolution failed, or all socket connections to the endpoint failed.
[ERROR] [2020-08-17T13:43:16Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:17Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:18Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:19Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:20Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:21Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:22Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:23Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:23Z] [00007f627bc0d700] [channel-bootstrap] - id=0x3a87988dbb40: dns resolution failed, or all socket connections to the endpoint failed.
[ERROR] [2020-08-17T13:43:24Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:25Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:26Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:27Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:28Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:29Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:30Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:31Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:32Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:33Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:34Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:35Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:36Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:37Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:38Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:39Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:39Z] [00007f627bc0d700] [channel-bootstrap] - id=0x3a87988dbb40: dns resolution failed, or all socket connections to the endpoint failed.
[ERROR] [2020-08-17T13:43:40Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:41Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:42Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:43Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:44Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:45Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:46Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:47Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:48Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:49Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:50Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:51Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:52Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:53Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:54Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:55Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:56Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:57Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:58Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:43:59Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:00Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:01Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:02Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:03Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:04Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:05Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:06Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:07Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:08Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:11Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:11Z] [00007f627bc0d700] [channel-bootstrap] - id=0x3a87988dbb40: dns resolution failed, or all socket connections to the endpoint failed.
[ERROR] [2020-08-17T13:44:12Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:13Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:14Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:15Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:16Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:17Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:18Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:19Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:20Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:21Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:22Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:23Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:24Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:25Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:26Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:27Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:28Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:29Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:30Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:31Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:32Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:33Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:34Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:35Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:36Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:37Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:38Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:39Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:44:40Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:15Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:15Z] [00007f627bc0d700] [channel-bootstrap] - id=0x3a87988dbb40: dns resolution failed, or all socket connections to the endpoint failed.
[ERROR] [2020-08-17T13:45:16Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:17Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:18Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:19Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:20Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:21Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:22Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:23Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:24Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:25Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:26Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:27Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:28Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:29Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:30Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:31Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:32Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:33Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:34Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:35Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:36Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:37Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:38Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:39Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:40Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:41Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:42Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:43Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[ERROR] [2020-08-17T13:45:44Z] [00007f627bc0d700] [dns] - static: getaddrinfo failed with error_code -3
[WARN ] [2020-08-17T13:47:23Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[ERROR] [2020-08-17T13:47:23Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: connect failed with error code 101.
[INFO ] [2020-08-17T13:47:23Z] [00007f6281c5a700] [dns] - id=0x3a87988e9768: recording failure for record 2600:1f00:6000::385:25fb for a1lhfls3yg5tly-ats.iot.us-east-2.amazonaws.com, moving to bad list
[ERROR] [2020-08-17T13:47:23Z] [00007f6281c5a700] [channel-bootstrap] - id=0x3a87988dbb40: failed to create socket with error 1049
[WARN ] [2020-08-17T13:47:23Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[INFO ] [2020-08-17T13:47:23Z] [00007f6281c5a700] [socket] - id=0x3a8798bc5b00 fd=72: connection success
ssn-content-player: ../nptl/pthread_mutex_lock.c:352: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != ESRCH || !robust' failed.
Signal received: 0, errno: 0
################################################################################
Resolved stacktrace:
################################################################################
0x00007f6281dd486b: ?? ??:0
0x00000000000b1783: s_print_stack_trace at module.c:?
0x00000000000110e0: __restore_rt at ??:?
0x00007f62916cdfff: ?? ??:0
0x00007f62916cf42a: ?? ??:0
0x000000000002be67: uselocale at ??:?
0x000000000002bf12: __assert_fail at ??:?
0x00000000000099fd: __pthread_mutex_lock_full at ??:?
0x00005555e4a4f489: ?? ??:0
################################################################################
Raw stacktrace:
################################################################################
/usr/share/ssn/player/resources/app/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_backtrace_print+0x4b) [0x7f6281dd486b]
/usr/share/ssn/player/resources/app/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xb1783) [0x7f6281d0c783]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0) [0x7f6297c580e0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7f62916cdfff]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f62916cf42a]
/lib/x86_64-linux-gnu/libc.so.6(+0x2be67) [0x7f62916c6e67]
/lib/x86_64-linux-gnu/libc.so.6(+0x2bf12) [0x7f62916c6f12]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x99fd) [0x7f6297c509fd]
/usr/share/ssn/player/ssn-content-player(uv_mutex_lock+0x9) [0x5555e4a4f489]
```

**Comment by TingDaoK** [comment] 2020-08-17 16:52
Can you provide trace level log info? For the log for now, it shows the connection successfully detected the connection lost and reconnected successfully as well at 13:47:23. After that something went wrong, I cannot tell what's the cause with the given information.

**Comment by jarredkenny** [comment] 2020-08-18 11:25
@TingDaoK here is the same crash with a log level of 6/trace. 

https://gist.github.com/jarredkenny/b98654cc36988b2161c2aeb277a14ad1

**Comment by TingDaoK** [comment] 2020-08-18 21:11
Thank you for the log. It helps us find a bug and get it fixed. Not 100% sure it is the root cause, we will update here once the release is out with the fix!

**Comment by cupostv** [comment] 2020-08-20 08:03
@TingDaoK Hi, just to update you from my side. I am still having the same issue on Windows 10 and on WSL1. When I switch to different network and use Raspberry PI, I am not getting the error, everything works as it should.
Is it possible that it's some network restriction or something similar?
I will still try Windows 10 in the network where it works on RPI and update you.

**Comment by rccarper** [comment] 2020-08-20 14:16
We haven't cut a new release just yet with the fix.  But, I believe it should be platform independent, so it would be interesting if you're not encountering a problem on Windows 10 with a different network.  I'll respond back once the new release is out, which should be soon!

**Comment by rccarper** [comment] 2020-08-20 21:37
Quick update: it will be a little bit longer until we have the release out--we'll try to get it out before the weekend.  Pulling in the above fix to this SDK pulls in other changes as well, which requires some additional testing.  After some additional investigation, it does look like the above fix addresses the root cause of the crash though.  I'll respond back once I have another update!

**Comment by rccarper** [comment] 2020-08-25 03:24
Thank you for your patience!  The new release, v1.3.0, has the fix.  I'll close this ticket, but please feel free to re-open if you run into an issue with the fix.

**Closed by rccarper** 2020-08-25 03:24 UTC
Labels: guidance

**Comment by cupostv** [comment] 2020-08-25 06:58
Thanks for the effort. I tested it and now everything works perfectly on Win 10, WSL and RPI. There is no crash, and connection is resumed correctly.

**Comment by jarredkenny** [comment] 2020-08-27 11:36
Confirmed working as well on Debian. There is no longer a crash after changing wireless networks. Thank you!
